title: "Huan WU"
author: "Haley WU"
description: "Hong Kong Polytechnic University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false       # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md"}
  - {url: "haley.pdf",title:CV}
  - {file: "research.md",title: Research}
  - {file: "project.md",title: Project}
  - {file: "blog.md",title: Blog}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:hkpolyu.wu@polyu.edu.hk"}
  - {title: Google Scholar, icon: google scholar, url: "https://scholar.google.com/citations?user=kddf8fUAAAAJ&hl=en"}
  - {title: Strava, icon: strava, url: "https://www.strava.com/athletes/100939052/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed

